
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.4 EDK_MS4.81d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartlite.h"

/*
* The configuration table for devices
*/

XUartLite_Config XUartLite_ConfigTable[] =
{
	{
		XPAR_RS232_DEVICE_ID,
		XPAR_RS232_BASEADDR,
		XPAR_RS232_BAUDRATE,
		XPAR_RS232_USE_PARITY,
		XPAR_RS232_ODD_PARITY,
		XPAR_RS232_DATA_BITS
	},
	{
		XPAR_RS232_USB_DEVICE_ID,
		XPAR_RS232_USB_BASEADDR,
		XPAR_RS232_USB_BAUDRATE,
		XPAR_RS232_USB_USE_PARITY,
		XPAR_RS232_USB_ODD_PARITY,
		XPAR_RS232_USB_DATA_BITS
	}
};


