--------------------------------------------------------------------------------
-- Copyright (c) 1995-2008 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 10.1.03
--  \   \         Application : xaw2vhdl
--  /   /         Filename : DCM2PLL.vhd
-- /___/   /\     Timestamp : 02/11/2011 10:34:28
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-st M:\MASTER\COMPET\compet_readout\ClkRst\\DCM2PLL.xaw M:\MASTER\COMPET\compet_readout\ClkRst\\DCM2PLL
--Design Name: DCM2PLL
--Device: xc5vlx50t-1ff1136
--
-- Module DCM2PLL
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT0 = 0.154 ns
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT1 = 0.154 ns
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT2 = 0.154 ns
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT3 = 0.154 ns
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT4 = 0.154 ns

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity DCM2PLL is
   port ( CLKIN_N_IN        : in    std_logic; 
          CLKIN_P_IN        : in    std_logic; 
          USER_RST_IN       : in    std_logic; 
          CLKIN_IBUFGDS_OUT : out   std_logic; 
          CLKOUT0_OUT       : out   std_logic; 
          CLKOUT1_OUT       : out   std_logic; 
          CLKOUT2_OUT       : out   std_logic; 
          CLKOUT3_OUT       : out   std_logic; 
          CLKOUT4_OUT       : out   std_logic; 
          LOCKED_OUT        : out   std_logic);
end DCM2PLL;

architecture BEHAVIORAL of DCM2PLL is
   signal CLKFBOUT_CLKFBIN   : std_logic;
   signal CLKFB_IN           : std_logic;
   signal CLKIN_IBUFGDS      : std_logic;
   signal CLKOUT0_BUF        : std_logic;
   signal CLKOUT1_BUF        : std_logic;
   signal CLKOUT2_BUF        : std_logic;
   signal CLKOUT3_BUF        : std_logic;
   signal CLKOUT4_BUF        : std_logic;
   signal CLK0_BUF           : std_logic;
   signal DCM_LOCKED_INV_IN  : std_logic;
   signal FDS_Q_OUT          : std_logic;
   signal FD1_Q_OUT          : std_logic;
   signal FD2_Q_OUT          : std_logic;
   signal FD3_Q_OUT          : std_logic;
   signal GND_BIT            : std_logic;
   signal GND_BUS_5          : std_logic_vector (4 downto 0);
   signal GND_BUS_7          : std_logic_vector (6 downto 0);
   signal GND_BUS_16         : std_logic_vector (15 downto 0);
   signal OR3_O_OUT          : std_logic;
   signal PLL_LOCKED_INV_RST : std_logic;
   signal RST_IN             : std_logic;
   signal VCC_BIT            : std_logic;
begin
   GND_BIT <= '0';
   GND_BUS_5(4 downto 0) <= "00000";
   GND_BUS_7(6 downto 0) <= "0000000";
   GND_BUS_16(15 downto 0) <= "0000000000000000";
   VCC_BIT <= '1';
   CLKIN_IBUFGDS_OUT <= CLKIN_IBUFGDS;
   CLKIN_IBUFGDS_INST : IBUFGDS
      port map (I=>CLKIN_P_IN,
                IB=>CLKIN_N_IN,
                O=>CLKIN_IBUFGDS);
   
   CLKOUT0_BUFG_INST : BUFG
      port map (I=>CLKOUT0_BUF,
                O=>CLKOUT0_OUT);
   
   CLKOUT1_BUFG_INST : BUFG
      port map (I=>CLKOUT1_BUF,
                O=>CLKOUT1_OUT);
   
   CLKOUT2_BUFG_INST : BUFG
      port map (I=>CLKOUT2_BUF,
                O=>CLKOUT2_OUT);
   
   CLKOUT3_BUFG_INST : BUFG
      port map (I=>CLKOUT3_BUF,
                O=>CLKOUT3_OUT);
   
   CLKOUT4_BUFG_INST : BUFG
      port map (I=>CLKOUT4_BUF,
                O=>CLKOUT4_OUT);
   
   CLK0_BUFG_INST : BUFG
      port map (I=>CLK0_BUF,
                O=>CLKFB_IN);
   
   DCM_ADV_INST : DCM_ADV
   generic map( CLK_FEEDBACK => "1X",
            CLKDV_DIVIDE => 2.0,
            CLKFX_DIVIDE => 1,
            CLKFX_MULTIPLY => 4,
            CLKIN_DIVIDE_BY_2 => FALSE,
            CLKIN_PERIOD => 10.000,
            CLKOUT_PHASE_SHIFT => "FIXED",
            DCM_AUTOCALIBRATION => TRUE,
            DCM_PERFORMANCE_MODE => "MAX_SPEED",
            DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
            DFS_FREQUENCY_MODE => "LOW",
            DLL_FREQUENCY_MODE => "LOW",
            DUTY_CYCLE_CORRECTION => TRUE,
            FACTORY_JF => x"F0F0",
            PHASE_SHIFT => 1,
            STARTUP_WAIT => FALSE,
            SIM_DEVICE => "VIRTEX5")
      port map (CLKFB=>CLKFB_IN,
                CLKIN=>CLKIN_IBUFGDS,
                DADDR(6 downto 0)=>GND_BUS_7(6 downto 0),
                DCLK=>GND_BIT,
                DEN=>GND_BIT,
                DI(15 downto 0)=>GND_BUS_16(15 downto 0),
                DWE=>GND_BIT,
                PSCLK=>GND_BIT,
                PSEN=>GND_BIT,
                PSINCDEC=>GND_BIT,
                RST=>RST_IN,
                CLKDV=>open,
                CLKFX=>open,
                CLKFX180=>open,
                CLK0=>CLK0_BUF,
                CLK2X=>open,
                CLK2X180=>open,
                CLK90=>open,
                CLK180=>open,
                CLK270=>open,
                DO=>open,
                DRDY=>open,
                LOCKED=>DCM_LOCKED_INV_IN,
                PSDONE=>open);
   
   FDS_INST : FDS
      port map (C=>CLKIN_IBUFGDS,
                D=>GND_BIT,
                S=>GND_BIT,
                Q=>FDS_Q_OUT);
   
   FD1_INST : FD
      port map (C=>CLKIN_IBUFGDS,
                D=>FDS_Q_OUT,
                Q=>FD1_Q_OUT);
   
   FD2_INST : FD
      port map (C=>CLKIN_IBUFGDS,
                D=>FD1_Q_OUT,
                Q=>FD2_Q_OUT);
   
   FD3_INST : FD
      port map (C=>CLKIN_IBUFGDS,
                D=>FD2_Q_OUT,
                Q=>FD3_Q_OUT);
   
   INV_INST : INV
      port map (I=>DCM_LOCKED_INV_IN,
                O=>PLL_LOCKED_INV_RST);
   
   OR2_INST : OR2
      port map (I0=>USER_RST_IN,
                I1=>OR3_O_OUT,
                O=>RST_IN);
   
   OR3_INST : OR3
      port map (I0=>FD3_Q_OUT,
                I1=>FD2_Q_OUT,
                I2=>FD1_Q_OUT,
                O=>OR3_O_OUT);
   
   PLL_ADV_INST : PLL_ADV
   generic map( BANDWIDTH => "OPTIMIZED",
            CLKIN1_PERIOD => 10.000,
            CLKIN2_PERIOD => 10.000,
            CLKOUT0_DIVIDE => 10,
            CLKOUT1_DIVIDE => 10,
            CLKOUT2_DIVIDE => 10,
            CLKOUT3_DIVIDE => 10,
            CLKOUT4_DIVIDE => 10,
            CLKOUT0_PHASE => 0.000,
            CLKOUT1_PHASE => 0.000,
            CLKOUT2_PHASE => 0.000,
            CLKOUT3_PHASE => 0.000,
            CLKOUT4_PHASE => 0.000,
            CLKOUT0_DUTY_CYCLE => 0.500,
            CLKOUT1_DUTY_CYCLE => 0.500,
            CLKOUT2_DUTY_CYCLE => 0.500,
            CLKOUT3_DUTY_CYCLE => 0.500,
            CLKOUT4_DUTY_CYCLE => 0.500,
            COMPENSATION => "DCM2PLL",
            DIVCLK_DIVIDE => 1,
            CLKFBOUT_MULT => 10,
            CLKFBOUT_PHASE => 0.0,
            REF_JITTER => 0.000000)
      port map (CLKFBIN=>CLKFBOUT_CLKFBIN,
                CLKINSEL=>VCC_BIT,
                CLKIN1=>CLK0_BUF,
                CLKIN2=>GND_BIT,
                DADDR(4 downto 0)=>GND_BUS_5(4 downto 0),
                DCLK=>GND_BIT,
                DEN=>GND_BIT,
                DI(15 downto 0)=>GND_BUS_16(15 downto 0),
                DWE=>GND_BIT,
                REL=>GND_BIT,
                RST=>PLL_LOCKED_INV_RST,
                CLKFBDCM=>open,
                CLKFBOUT=>CLKFBOUT_CLKFBIN,
                CLKOUTDCM0=>open,
                CLKOUTDCM1=>open,
                CLKOUTDCM2=>open,
                CLKOUTDCM3=>open,
                CLKOUTDCM4=>open,
                CLKOUTDCM5=>open,
                CLKOUT0=>CLKOUT0_BUF,
                CLKOUT1=>CLKOUT1_BUF,
                CLKOUT2=>CLKOUT2_BUF,
                CLKOUT3=>CLKOUT3_BUF,
                CLKOUT4=>CLKOUT4_BUF,
                CLKOUT5=>open,
                DO=>open,
                DRDY=>open,
                LOCKED=>LOCKED_OUT);
   
end BEHAVIORAL;


