--------------------------------------------------------------------------------
-- Copyright (c) 1995-2008 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 10.1.03
--  \   \         Application : xaw2vhdl
--  /   /         Filename : PLL_CTU.vhd
-- /___/   /\     Timestamp : 02/09/2011 13:51:58
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-st \\aristoteles\kimei\MASTER\COMPET\compet_readout\ClkRst\PLL_CTU.xaw \\aristoteles\kimei\MASTER\COMPET\compet_readout\ClkRst\PLL_CTU
--Design Name: PLL_CTU
--Device: xc5vlx50t-1ff1136
--
-- Module PLL_CTU
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT0 = 0.160 ns
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT1 = 0.160 ns
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT2 = 0.160 ns
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT3 = 0.160 ns
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT4 = 0.160 ns

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity PLL_CTU is
   port ( CLKINSEL_IN : in    std_logic; 
          CLKIN1_IN   : in    std_logic; 
          CLKIN2_IN   : in    std_logic; 
          RST_IN      : in    std_logic; 
          CLKOUT0_OUT : out   std_logic; 
          CLKOUT1_OUT : out   std_logic; 
          CLKOUT2_OUT : out   std_logic; 
          CLKOUT3_OUT : out   std_logic; 
          CLKOUT4_OUT : out   std_logic; 
          LOCKED_OUT  : out   std_logic);
end PLL_CTU;

architecture BEHAVIORAL of PLL_CTU is
   signal CLKFBOUT_CLKFBIN : std_logic;
   signal CLKIN1_IBUFG     : std_logic;
   signal CLKIN2_IBUFG     : std_logic;
   signal CLKOUT0_BUF      : std_logic;
   signal CLKOUT1_BUF      : std_logic;
   signal CLKOUT2_BUF      : std_logic;
   signal CLKOUT3_BUF      : std_logic;
   signal CLKOUT4_BUF      : std_logic;
   signal GND_BIT          : std_logic;
   signal GND_BUS_5        : std_logic_vector (4 downto 0);
   signal GND_BUS_16       : std_logic_vector (15 downto 0);
begin
   GND_BIT <= '0';
   GND_BUS_5(4 downto 0) <= "00000";
   GND_BUS_16(15 downto 0) <= "0000000000000000";
   CLKIN1_IBUFG_INST : IBUFG
      port map (I=>CLKIN1_IN,
                O=>CLKIN1_IBUFG);
   
   CLKIN2_IBUFG_INST : IBUFG
      port map (I=>CLKIN2_IN,
                O=>CLKIN2_IBUFG);
   
   CLKOUT0_BUFG_INST : BUFG
      port map (I=>CLKOUT0_BUF,
                O=>CLKOUT0_OUT);
   
   CLKOUT1_BUFG_INST : BUFG
      port map (I=>CLKOUT1_BUF,
                O=>CLKOUT1_OUT);
   
   CLKOUT2_BUFG_INST : BUFG
      port map (I=>CLKOUT2_BUF,
                O=>CLKOUT2_OUT);
   
   CLKOUT3_BUFG_INST : BUFG
      port map (I=>CLKOUT3_BUF,
                O=>CLKOUT3_OUT);
   
   CLKOUT4_BUFG_INST : BUFG
      port map (I=>CLKOUT4_BUF,
                O=>CLKOUT4_OUT);
   
   PLL_ADV_INST : PLL_ADV
   generic map( BANDWIDTH => "OPTIMIZED",
            CLKIN1_PERIOD => 10.000,
            CLKIN2_PERIOD => 10.000,
            CLKOUT0_DIVIDE => 8,
            CLKOUT1_DIVIDE => 8,
            CLKOUT2_DIVIDE => 8,
            CLKOUT3_DIVIDE => 8,
            CLKOUT4_DIVIDE => 8,
            CLKOUT0_PHASE => 0.000,
            CLKOUT1_PHASE => 0.000,
            CLKOUT2_PHASE => 0.000,
            CLKOUT3_PHASE => 0.000,
            CLKOUT4_PHASE => 0.000,
            CLKOUT0_DUTY_CYCLE => 0.500,
            CLKOUT1_DUTY_CYCLE => 0.500,
            CLKOUT2_DUTY_CYCLE => 0.500,
            CLKOUT3_DUTY_CYCLE => 0.500,
            CLKOUT4_DUTY_CYCLE => 0.500,
            COMPENSATION => "SYSTEM_SYNCHRONOUS",
            DIVCLK_DIVIDE => 1,
            CLKFBOUT_MULT => 8,
            CLKFBOUT_PHASE => 0.0,
            REF_JITTER => 0.005000)
      port map (CLKFBIN=>CLKFBOUT_CLKFBIN,
                CLKINSEL=>CLKINSEL_IN,
                CLKIN1=>CLKIN1_IBUFG,
                CLKIN2=>CLKIN2_IBUFG,
                DADDR(4 downto 0)=>GND_BUS_5(4 downto 0),
                DCLK=>GND_BIT,
                DEN=>GND_BIT,
                DI(15 downto 0)=>GND_BUS_16(15 downto 0),
                DWE=>GND_BIT,
                REL=>GND_BIT,
                RST=>RST_IN,
                CLKFBDCM=>open,
                CLKFBOUT=>CLKFBOUT_CLKFBIN,
                CLKOUTDCM0=>open,
                CLKOUTDCM1=>open,
                CLKOUTDCM2=>open,
                CLKOUTDCM3=>open,
                CLKOUTDCM4=>open,
                CLKOUTDCM5=>open,
                CLKOUT0=>CLKOUT0_BUF,
                CLKOUT1=>CLKOUT1_BUF,
                CLKOUT2=>CLKOUT2_BUF,
                CLKOUT3=>CLKOUT3_BUF,
                CLKOUT4=>CLKOUT4_BUF,
                CLKOUT5=>open,
                DO=>open,
                DRDY=>open,
                LOCKED=>LOCKED_OUT);
   
end BEHAVIORAL;


